Web/Web/Controllers/LoginController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using System.Web.Security;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using Web.Models;
using Web.Models.Repository;
using System.Net;
using System.Net.Mail;
using System.Text.RegularExpressions;
using log4net;
using System.Collections.Generic;

namespace Web.Controllers
{

    [Authorize]
    public class LoginController : Controller
    {
        Repo repository;
        private static readonly ILog Log = LogManager.GetLogger("LOGGER");

        public LoginController()
        {
            repository = new Repo();
        }
        //
        // GET: /Login/
        [AllowAnonymous]
        public ActionResult Index(string returnUrl)
        {         
            //Если пользователь зарегистрирован, но вас кинуло именно сюда, значит вам на ту страницу нельзя 401
         //   if (WebSecurity.IsAuthenticated && WebSecurity.Initialized)
         //       return RedirectToAction("Error_401", "Login");
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        //       [ValidateJsonAntiForgeryToken]
        public ActionResult Index(LoginModel model)
        {
            if (ModelState.IsValid && WebSecurity.Login(model.UserName, model.Password, persistCookie: model.RememberMe))
            {

                uk_profile uk_u = null;
                uk_profile uk_a = null;
                try
                {
                    Account_model result = new Account_model();
                    result.id = WebSecurity.GetUserId(model.UserName);
                    result.Login = model.UserName;

                    UserProfile user = repository.UserProfile.Where(p => p.UserId.Equals(result.id)).SingleOrDefault();
                    Admtszh admtszh = repository.Admtszh.Where(p => p.AdmtszhId.Equals(result.id)).SingleOrDefault();

                    if ((user == null) && (admtszh == null))
                    {
                        //Пользователь не принадлежайщий никакому ТСЖ  
                        //т.е не имеющий роли, просто входит
                        FormsAuthentication.SetAuthCookie(model.UserName, model.RememberMe);
                        return Json(result);
                    }

                    string requestDomain = Request.Headers["host"];
                    if (user != null)
                        uk_u = repository.uk_profile.Where(p => p.id.Equals(user.id_uk)).SingleOrDefault();
                    if (admtszh != null)
                        uk_a = repository.uk_profile.Where(p => p.id.Equals(admtszh.id_uk)).SingleOrDefault();
                    //Если пользователь имеет несколько ролей в разных ТСЖ
                    var myList = new List<string>();
                    foreach (var role in Roles.GetRolesForUser(model.UserName))
                    {
                        if (user != null) {
                            if (requestDomain.Equals(uk_u.host) && role.Equals("User"))
                            {
                                myList.Add(role);
                            }
                        }
                        if (admtszh != null) {
                            if (requestDomain.Equals(uk_a.host) && role.Equals("Moder"))
                            {
                                myList.Add(role);
                            }
                        }
                    }

                    result.Roles = myList.ToArray();

                    if (result.Roles.Count() >0) {
                        foreach (var role in result.Roles)
                        {
                            if (role.Equals("User"))
                            {
                                if (user != null)
                                {
                                    if (requestDomain.Equals(uk_u.host))
                                    {
                                        //User have direct company
                                        FormsAuthentication.SetAuthCookie(model.UserName, model.RememberMe);
                                        return Json(result);
                                    }
                                    else
                                    {
                                        //User have no current direct company
                                        //TempData["message"] = string.Format("Хост: \"{0}\" ", requestDomain);
                                        //WebSecurity.Logout();
                                        return Json(new string[] { "Error", "Имя пользователя или пароль не принадлежат данному домену" });
                                    }
                                }
                            }
                            if (role.Equals("Moder"))
                            {
                                if (admtszh != null)
                                {
                                    if (requestDomain.Equals(uk_a.host))
                                    {
                                        //User have direct company
                                        FormsAuthentication.SetAuthCookie(model.UserName, model.RememberMe);
                                        return Json(result);
                                        //        return new HttpStatusCodeResult(200, "{id:"+ WebSecurity.CurrentUserId.ToString() + "}");
                                    }
                                    else
                                    {
                                        //User have no current direct company
                                        //TempData["message"] = string.Format("Хост: \"{0}\" ", requestDomain);
                                        //
                                        return Json(new string[] { "Error", "Имя пользователя или пароль не принадлежат данному домену" });

                                    }

                                }

                            }
                            if (role.Equals("Admin"))
                            {
                                //Админов просто авторизовать
                                FormsAuthentication.SetAuthCookie(model.UserName, model.RememberMe);
                                return Json(result);
                            }
                        }
                        WebSecurity.Logout();
                    }

                }
                catch (Exception ex)
                {
                    Logger.Log.Error("Внутренняя ошибка при авторизации пользователя" + model.UserName, ex);                  
                }

            }
            return Json(new string[] { "Error", "Имя пользователя или пароль указаны неверно." });
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Register()
        {           
            return View();
        }

        [HttpPost]
        //        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Register(RegisterModel model)
        {
            if (WebSecurity.UserExists(model.UserName))
            {
                return Json("Error", "Пользователь с таким логином уже существует");
            }

            if (!WebSecurity.IsAuthenticated)
            {
              
                if (ModelState.IsValid)
                {
                    try
                    {
                        WebSecurity.CreateUserAndAccount(model.UserName, model.Password);
                        //Membership.CreateUser(model.UserName, model.Password, model.Email,
                        //passwordQuestion: null, passwordAnswer: null, isApproved: true,
                        //providerUserKey: null, status: out createStatus);
                        WebSecurity.RequireRoles();

                        //Send E-mail
                        string title = "Добро пожаловать!";
                        string message = "Вы зарегистрировались в системе http://mytsn.ru\n"
                            + "Ваши логин: " + model.UserName 
                            +"\n Пароль: " + model.Password 
                            + "\nДля получения полного доступа к функционалу Вам необходимо заполнить анкету и отправить запрос на активацию.";

                        SendMail("smtp.yandex.ru", "cloudsolution@bitrix24.ru", "321654as", model.UserName, title, message);

                        WebSecurity.Login(model.UserName, model.Password);
                        Account_model result = new Account_model();
                        result.id = WebSecurity.CurrentUserId;
                        result.Login = WebSecurity.CurrentUserName;
                        result.Roles = Roles.GetRolesForUser();
                        return Json(result);

                        
                    }
                    catch (MembershipCreateUserException ex)
                    {
                        ModelState.AddModelError("Ошибка при регистрации: ", ErrorCodeToString(ex.StatusCode));
                        Logger.Log.Error("Ошибка при регистрации: ", ex);
                        return Json("Error", "Ошибка при регистрации: " + ErrorCodeToString(ex.StatusCode));
                    }
                }
                if (string.IsNullOrEmpty(model.UserName))
                {
                    return Json("Error", "Введите E-mail");
                }
                if (string.IsNullOrEmpty(model.Password))
                {
                    return Json("Error", "Пустой пароль");
                }

            }
            WebSecurity.Logout();
            return Json("Error", "Ошибка при регистрации");
        }

        [AllowAnonymous]
        public ActionResult LogOut(string ReturnUrl)
        {
            WebSecurity.Logout();
            return new HttpStatusCodeResult(200);
        }

        [HttpGet]
        [AllowAnonymous]

Web/Web/Controllers/NavController.cs
//using System;
using System.Collections.Generic;
using System.Linq;
//using System.Web;
using System.Web.Mvc;
//using System.Data.SqlClient;
using System.Data;
//using Web.Models;
using Web.Models.Repository;
using Web.Models;
using WebMatrix.WebData;
using Web.Filters;

namespace Web.Controllers
{

    public class NavController : Controller
    {
        //
        // GET: /Nav/
        Repo repository;

        public NavController()
        {
            repository = new Repo();
        }

        public PartialViewResult Menu(int menu_id = 0)
        {
            //Связываемся с нашей БД
            //Repo p = new Repo();
            //Отправляем результат предствалению
            return PartialView(repository.MenuItems.Where(q => q.menu_id.Equals(menu_id)).OrderBy(a => a.id));
        }



        public PartialViewResult Menu_main(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Articles
                .Select(title => title.title)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }

        public PartialViewResult menu_top(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Articles
                .Select(title => title.title)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }


        
        public PartialViewResult menu_moder()
        {
            return PartialView();
        }
    }
}

Web/Web/Views/Shared/_AdminMenu.cshtml
@if (User.IsInRole("Admin"))
{
    <ul>
        <li>@Html.ActionLink("Cтатьи", "Articles")</li>
        <li>@Html.ActionLink("Пользователи", "ViewUsers", "Admin")</li>
        <li>@Html.ActionLink("Модераторы", "ViewModers", "Admin")</li>
        <li>@Html.ActionLink("УК и ТСЖ", "ViewUk", "Admin")</li>
        <li>@Html.ActionLink("Управление ролями", "ViewRoles", "Admin")</li>
    </ul>
}

Web/Web/Views/Shared/_HomeMenu.cshtml
<ul>
    <li>@Html.ActionLink("Главная", "Index", new { controller = "Home",  id=1}, new { @class = "l_menu" })</li>
    <li>@Html.ActionLink("Контакты", "Index", new { controller = "Home", id = 2 }, new { @class = "l_menu" })</li>
</ul>

Web/Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Административный раздел</title>
    <meta charset="utf-8" />
    <link href="~/Styles/style.css" rel="stylesheet" />
    <link href="~/Styles/error.css" rel="stylesheet" />
</head>
<body>
    <div class="main">
        <header>
        <div class="logo">LOGO
        </div> 
        </header>
         <nav>
            <div class="l_menu">
                @Html.Partial("~/Views/Shared/_AdminMenu.cshtml")
            </div>
        </nav>
        <div class="content">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
        <footer>
            <div class="footer">
                Все права защищены. CloudsSolution © 2015.
                @Html.ActionLink("Вернуться на сайт", "Index", "User")
            </div>
        </footer>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Web/Views/Shared/_LayoutLogin.cshtml
@if (Request.IsAuthenticated)
{
    @:Вы вошли как 
    <strong>
        @User.Identity.Name
    </strong>
    <span>
        @Html.ActionLink("Выйти", "LogoOut", "Login")
    </span>
}
else
{
    <span>@Html.ActionLink("Войти", "Index", "Login")</span>
    <span>@Html.ActionLink("Регистрация", "Register", "Login" )</span>
}

Web/Web/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>

<html lang="ru" ng-app="HomeApp">

<head>
    @*<base href="/home">*@
    <meta charset="utf-8">
    <title>Business clean web templates</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="~/Scripts/angular-1.5.6/angular.js"></script>
    <script src="~/Scripts/angular-1.5.6/angular-animate.js"></script>
    <script src="~/Scripts/angular-1.5.6/angular-route.js"></script>
    <script src="~/Scripts/angular-1.5.6/angular-cookies.js"></script>
    <script src="~/Scripts/angular-1.5.6/angular-resource.js"></script>
    <script src="~/Scripts/angular-1.5.6/angular-sanitize.js"></script>
    <script src="~/Scripts/bootstrap-master/ui-bootstrap-tpls-1.2.1.js"></script>
    <script src="~/Scripts/js/Controller.js"></script>
    <script src="~/Scripts/js/login.js"></script>
    <script src="~/Scripts/js/UserService.js"></script>
    <script src="~/Scripts/js/OperService.js"></script>

    <link href="~/Styles/themes/css/bootstrap.min.css" type="text/css" media="screen" id="callCss" rel="stylesheet" />
    <link href="~/Styles/themes/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css">
    <link href="~/Styles/themes/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="~/Styles/themes/css/base.css" rel="stylesheet" type="text/css">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <link href="~/Styles/themes/css/font-awesome-ie7.css" rel="stylesheet" />
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


</head>

<body ng-controller="LoginInfoCtrl">
    <section id="navbar">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="btn btn-navbar" ng-init="navCollapsed = false" ng-click="navCollapsed = !navCollapsed" ng-class="{'collapsed':!navCollapsed}">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1><a class="brand" href="#/"> Business <small>  Ltd. {{navHeight}}</small></a></h1>
                        <div ng-class="{true:'nav-collapse collapse', false:'nav-collapse in collapse'}[navCollapsed]" ng-style="{{navHeight}}">
                            <ul class="nav pull-right" style="top: 0px;">
                                <li><a href="#/">Главная</a></li>
                                @Html.Action("menu_top", "Nav")


                                <!-- Simple dropdown -->
                                <li uib-dropdown on-toggle="toggled(open)" ng-show="Session.currentUser">
                                    <a href="#/" id="simple-dropdown" uib-dropdown-toggle>
                                        <i class="icon-user"></i> Меню пользователя
                                    </a>
                                    <ul uib-dropdown-menu aria-labelledby="simple-dropdown">
                                        <li><a href="#/meters">Счетчики</a></li>
                                        <li><a href="#/feedback">Обратная связь</a></li>
                                        <li class=""><a href="#/profile">Профиль</a></li>
                                        <li class=""><a href="#/">Support</a></li>
                                    </ul>
                                </li>

                                @*<ul uib-dropdown-menu aria-labelledby="simple-dropdown">
                                        <li><a href="#/meters">Счетчики</a></li>
                                        <li><a href="#/feedback">Обратная связь</a></li>
                                        <li class=""><a href="#/profile">Профиль</a></li>
                                        <li class=""><a href="contact.html">Support</a></li>
                                    </ul>*@


                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--Header Ends================================================ -->

    <section id="bannerSection" style="background:url(../../Styles/themes/images/banner/contact.png) no-repeat center center #000;">
        <div class="container">
            <h1 id="pageTitle">
                Contact <small> :We love to hear from you</small>
                <span class="pull-right toolTipgroup">
                    <a href="#" data-placement="top" data-original-title="Find us on via facebook"><img style="width:45px" src="~/Styles/themes/images/facebook.png" alt="facebook" title="facebook"></a>
                    <a href="#" data-placement="top" data-original-title="Find us on via twitter"><img style="width:45px" src="~/Styles/themes/images/twitter.png" alt="twitter" title="twitter"></a>
                    <a href="#" data-placement="top" data-original-title="Find us on via youtube"><img style="width:45px" src="~/Styles/themes/images/youtube.png" alt="youtube" title="youtube"></a>
                </span>
            </h1>
        </div>
    </section>
    <!--Banner Ends================================================ -->
    <section id="bodySection" style="left: 0px">
        <div class="container">
            
            <hr class="soften">
            <div class="container">
                <div class="row">

                    <div class="span3">
                        <div class="well" style="padding: 8px 0;">
                            
                            <div ng-if="Session.currentUser" class="row-fluid">
                                Welcome, {{ Session.currentUser }}
                                <a class="navbar-brand" href="#/logout">Выйти</a>
                            </div>
                            <div ng-hide="Session.currentUser">
                                <div ng-controller="LoginCtrl" class="row-fluid">
                                    <div class="">
                                        <span ng-show="response[0]" class="label label-important">
                                            {{response[1]}}
                                        </span>
                                        <form class="form-inline">
                                            @*@Html.AntiForgeryToken()*@
                                            <div class="form-group">
                                                @*<label class="control-label">Логин :</label>*@
                                               <div class="col-md-10">
                                                    <input type="text" class="form-control text-box single-line" placeholder="Login" ng-model="credentials.username">
                                                </div>
											</div>
                                            <div class="form-group">
                                                @*<label class="control-label">Пароль:</label>*@
                                                <div class="col-md-10">
                                                    <input type="password" class="form-control text-box single-line" placeholder="Password" ng-model="credentials.password">
												</div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label"  for="optionsCheckbox">Запомнить</label>
                                                <label class="checkbox">
                                                    <input type="checkbox" id="optionsCheckbox" ng-model="credentials.RememberMe">
                                                </label>
                                            </div>
                                            <div class="form-actions">
                                                <button type="submit" class="btn btn-default" ng-click="login(credentials)">Войти</button>
                                            </div>
                                        </form>
                                        <div class="row-fluid"><a href="#/register" class="dropdown-toggle">Регистрация</a> <a href="#/RecoverPassSendMail" class="dropdown-toggle">Забыли пароль</a>
										</div>
                                    </div>
                                </div>
                            </div>
                            @if (User.IsInRole("Moder"))
                            {
                                @Html.Action("menu_moder", "Nav")
                            }
                            <!-- Single button -->
                            <div class="btn-group" id="Singlebutton" uib-dropdown is-open="status.isopen">
                                @*<button id="single-button" type="button" class="btn btn-primary" uib-dropdown-toggle ng-disabled="disabled">
                                        Меню администратора<span class="caret"></span>
                                    </button>*@
                                <ul uib-dropdown-menu role="menu" aria-labelledby="single-button"></ul>
                            </div>
                        </div>
                    </div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </section>
    <!--Body Ends================================================ -->
    <footer>
        Все права защищены. CloudsSolution © 2015.
    </footer>

    @RenderSection("Scripts", required: false)

</body>

</html>

Web/Web/Views/Shared/_LayoutUk.cshtml
<!DOCTYPE html>
<head>
<title>@ViewBag.Title</title>
<meta http-equiv="Content-Type" content="text/css; charset=UTF-8" />
    <link href="~/Styles/style.css" rel="stylesheet" />
    <link href="~/Styles/error.css" rel="stylesheet" />
</head>
<body>

<div class="login">              
 	@Html.Partial("~/Views/Shared/_LayoutLogin.cshtml")
</div>
<div class="main">
    <div class="header">
        <div class="header_resize">
            <div class="menu_nav">    
            @Html.Action("Menu_main", "Nav")
        
            </div>
            <div class="logo">
                <h1><a>LOGO <small>наше лого, подпись и тд</small></a></h1>
            </div>
    	    <div class="clr">   </div>
      
            <div class="headertext" >
            <h2>Read me first...</h2>         
            </div>
        </div>
    </div>

    <div class="content" >
        <div class="content_resize">
            <div class="mainbar">     
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success">@TempData["message"]</div>
                }              
                <div class="article" id="test" >
          
                @RenderBody()
                </div>    
            </div>
            <div class="gadget">      
	            @Html.Partial("_UserMenu")
            </div>
        </div>
    </div>
   
</div>
    <div class="footer">
    <div class="footer_resize">
        Все права защищены. CloudsSolution © 2015.
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Админ", "Index", "Admin")
            @:  ссылка видна только пользователю с ролью "Admin"
                }
        <div class="clr"></div>
    </div>
</div>
    @RenderSection("Scripts", required: false)

 
</body>
</html>

Web/Web/Views/Shared/_MainMenu.cshtml
    <ul>
        <li>@Html.ActionLink("Главная", "Index", new { controller = "User", id = "Главная" }, new { @class = "l_menu" })</li>
        <li>@Html.ActionLink("Контакты", "Index", new { controller = "User", id = "Контакты" }, new { @class = "l_menu" })</li>
    </ul>

Web/Web/Views/Shared/_UserMenu.cshtml
@if (WebSecurity.IsAuthenticated)
{
    if (User.IsInRole("Moder"))
    {
    <ul>
        <li>@Html.ActionLink("Профиль администратора", "profile", "Admtszh")</li>
        <li>@Html.ActionLink("Обращения от жильцов", "readFeedBack", "Admtszh")</li>
        <li>@Html.ActionLink("Список пользователей", "ViewUsers", "Admtszh")</li>
        <li>@Html.ActionLink("Список пользователей", "ViewCounters", "Admtszh")</li>
    </ul>
    }    
    <ul>  
        @if ((User.IsInRole("User") && !User.IsInRole("Moder")) || User.IsInRole("User") || (!User.IsInRole("User") && !User.IsInRole("Moder")))
        {
        <li>@Html.ActionLink("Профиль", "profile", "User")</li>  
        }
        @if (User.IsInRole("User"))
    {   
        <li>@Html.ActionLink("Обратная связь", "FeedBack", "User")</li>
        <li>@Html.ActionLink("Газовый счетчик", "Gas", "User")</li>
        <li>@Html.ActionLink("Электрический счетчик", "Energo", "User")</li>
        <li>@Html.ActionLink("Cчетчик холодной воды", "ColdWater", "User")</li>
        <li>@Html.ActionLink("Счетчик горячей воды", "HotWater", "User")</li>
        }  
</ul>
}